# -*- coding: utf-8 AA-*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QThread, pyqtSignal, pyqtSlot, QModelIndex, QObject, QPoint
from PyQt5.QtGui import QPixmap, QPainter, QColor, QFont, QImage
from pyqtgraph import PlotWidget
from PyQt5.QtWidgets import*

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 600)
        self.colors = [(183, 101, 224), (93, 131, 212), (49, 205, 222), (36, 214, 75), (214, 125, 36) ,(230, 78, 192), (209, 84, 65), (0, 184, 245)]
        #self.centralwidget = DiagramWidget(MainWindow)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")



        self.ComboBox_1 = QtWidgets.QComboBox(self.centralwidget)
        self.ComboBox_1.setObjectName("ComboBox_1")
        self.horizontalLayout_2.addWidget(self.ComboBox_1)

        self.refreshButton = QtWidgets.QPushButton(self.centralwidget)
        self.refreshButton.setObjectName("refreshButton")
        self.refreshButton.setText("Refresh")
        self.horizontalLayout_2.addWidget(self.refreshButton)

        """
        self.intervalInput = QtWidgets.QLineEdit(self.centralwidget)
        self.intervalInput.setObjectName("intervalInput")
        self.intervalInput.setPlaceholderText("Logging Interval (s)")
        self.intervalInput.setMaximumSize(QtCore.QSize(200, 16777215)) 
        self.horizontalLayout_2.addWidget(self.intervalInput)
        """


        """
        self.ConnectButton = QtWidgets.QPushButton(self.centralwidget)
        self.ConnectButton.setObjectName("ConnectButton")
        self.ConnectButton.setText("Connect")
        self.horizontalLayout_2.addWidget(self.ConnectButton)
        """
        
        self.saveDirectoryButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveDirectoryButton.setObjectName("saveDirectoryButton")
        self.saveDirectoryButton.setText("File Directory")
        self.horizontalLayout_2.addWidget(self.saveDirectoryButton)

        self.LogButton = QtWidgets.QPushButton(self.centralwidget)
        self.LogButton.setObjectName("LogButton")
        self.LogButton.setText("Log to file")
        self.horizontalLayout_2.addWidget(self.LogButton)
        #self.LogButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.fileLabel = QtWidgets.QLabel(self.centralwidget)
        self.fileLabel.setObjectName("fileLabel")
        #self.fileLabel.setMaximumSize(QtCore.QSize(100, 500))
        self.horizontalLayout_2.addWidget(self.fileLabel)

        
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        
        #to contain diagram and labels
        width = 308
        height = 700
        self.DiagramWidget = QtWidgets.QWidget(self.centralwidget)
        self.DiagramWidget.setFixedSize(width, height)
        self.DiagramLayout = QtWidgets.QStackedLayout(self.DiagramWidget)

        self.imageLabel = QtWidgets.QLabel()
        pixmap = QPixmap("diagram.png")
        pixmap = pixmap.scaled(width, height)
        self.imageLabel.setPixmap(pixmap)
        self.imageLabel.setGeometry(0, 0, width, height)

        self.DiagramLayout.addWidget(self.imageLabel)
        self.labels = []
        for i in range(8):
            label = QtWidgets.QLabel(self.DiagramWidget)
            label.setText(f"T{i+1}")
            label.setStyleSheet(f"font-weight: bold; font-size: 14px; color: white ; background-color: rgb{self.colors[i]}; border: 1px solid black;")
            label.setFixedSize(80, 40)
            #label.move(i*20, i*20)
            self.labels.append(label)
            
        self.labels[0].move(int(0.02*width),int(0.88*height))  #T1
        self.labels[1].move(int(0.14*width),int(0.80*height))  #T2
        self.labels[2].move(int(0.24*width),int(0.71*height))  #T3
        self.labels[3].move(int(0.64*width),int(0.55*height)) #T4
        self.labels[4].move(int(0.20*width),int(0.46*height))  #T5
        self.labels[5].move(int(0.66*width),int(0.41*height)) #T6
        self.labels[6].move(int(0.64*width),int(0.28*height)) #T7
        self.labels[7].move(int(0.26*width),int(0.1*height))   #T8
        self.horizontalLayout.addWidget(self.DiagramWidget)

        """
        spacerWidth = 300
        spacerItem = QtWidgets.QSpacerItem(spacerWidth, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        #spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        """                             
                       
        self.graphWidget = PlotWidget(self.centralwidget)
        self.graphWidget.setMinimumSize(QtCore.QSize(348, 0))
        self.graphWidget.setObjectName("PlotWidget") 
        self.horizontalLayout.addWidget(self.graphWidget)        
        
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkboxes = []
        for i in range(8):
            self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
            self.checkBox.setMaximumSize(QtCore.QSize(100,30))
            self.checkBox.setObjectName(f"T{i+1}")
            self.checkBox.setChecked(True)
            self.verticalLayout_2.addWidget(self.checkBox)
            self.checkBox.setStyleSheet(f"font-weight: bold; font-size: 14px; color: white; background-color: rgb{self.colors[i]}; border: 1px solid black;")
            self.checkboxes.append(self.checkBox)
        
        self.startStopButton = QtWidgets.QPushButton(self.centralwidget)
        self.startStopButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.startStopButton.setObjectName("startStopButton")
        self.verticalLayout_2.addWidget(self.startStopButton)
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.clearButton.setObjectName("clearButton")
        self.verticalLayout_2.addWidget(self.clearButton)



        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")

        """
        self.labels = []
        for i in range(8):
            self.label = QtWidgets.QLabel(self.centralwidget)
            self.label.setGeometry(QtCore.QRect(30, 150, 60, 16))
            self.label.setObjectName(f"T{i+1}")
            self.verticalLayout_4.addWidget(self.label)
            self.label.setStyleSheet(f"color: white; background-color: rgb{self.colors[i]}; border: 1px solid black;")
            self.labels.append(self.label)

        self.labels[0].move(100, 100)
        """
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1197, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        """
        #import
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.menuFile.addAction(self.actionImport)
        self.menubar.addAction(self.menuFile.menuAction())
        """
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Temperature Monitor"))

        for i in range(8):
            self.checkboxes[i].setText(_translate("MainWindow",f"T{i+1}"))
            self.labels[i].setText(_translate("MainWindow", f"T{i+1}"))

        self.startStopButton.setText(_translate("MainWindow", "Start/Stop"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
    
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        #self.actionImport.setText(_translate("MainWindow", "Import"))

    """

    @pyqtSlot(str, tuple)
    def updateData(self, current_time, temperatures):
        # update temp on one that is checked
        
        for i in range(8):
            if self.checkboxes[i].isChecked():
                if temperatures[i] != 'err':
                    self.labels[i].setText(f"T{i + 1}: {temperatures[i]}")
                    
                else:
                    self.labels[i].setText(f"T{i + 1}: --")
            else:
                self.labels[i].setText(f"T{i + 1}: --")
        
        active_ch = tuple(temperatures[i] if self.checkboxes[i].isChecked() else np.nan for i in range(8))
        self.model.appendData(current_time, *active_ch)
        #add plots...using data stored in PurifierModel
        self.time.append(current_time)
        for i in range(8):
            #plot the active channels
            if self.checkboxes[i].isChecked():
                self.data[i].append(temperatures[i])
                self.plotLines[i].setData(self.time, self.data[i])
            else:
                self.data[i].append(np.nan)
                #self.data[i].append(temperatures[i])  

    """
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
